{% set name = "conda-poetry-liaison" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/conda_poetry_liaison-{{ version }}.tar.gz
  sha256: 79bdc4b5ad989bcf20cdcd01580cf6d1b9ae8d123ca0dc7ca39707e2b2e6ac46

build:
  entry_points:
    - cpl-deps = conda_poetry_liaison.deps:main
    - cpl-clean = conda_poetry_liaison.clean:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
  run:
    - python >=3.9.0,<4.0.0
    - tomli >=2.0.1,<3.0.0
    - tomli-w >=1.0.0,<2.0.0

test:
  imports:
    - conda_poetry_liaison
  commands:
    - pip check
    - cpl-deps --help
    - cpl-clean --help
  requires:
    - pip

about:
  home: https://github.com/oasci/conda-poetry-liaison
  summary: Make conda and poetry communicate
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aalexmmaldonado
